# Generated by Django 3.1 on 2020-08-12 05:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('todo', '0002_auto_20200811_1820'),
    ]

    operations = [
        migrations.AddField(
            model_name='todoitem',
            name='createdby',
            field=models.CharField(default='', max_length=200),
        ),
    ]
