# Generated by Django 3.1 on 2020-08-12 06:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('todo', '0003_todoitem_createdby'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='todoitem',
            name='createdby',
        ),
    ]
